/** Small helpers every exporter needs. */

/** A banner saying where the file came from, in the target's comment syntax. */
export function header(title: string, comment: string): string {
  return [`${comment} ${title}`, `${comment} Generated by Drawrix. Edit the .dgm, not this file.`].join(
    '\n'
  )
}

/** Quote a name unless it is already a plain identifier for that language. */
export function quoteIf(name: string, bare: RegExp, quote: string): string {
  return bare.test(name) ? name : `${quote}${name.split(quote).join('')}${quote}`
}

/** A name reduced to letters, digits and underscores, for languages that insist. */
export function slug(name: string): string {
  const cleaned = name.replace(/[^A-Za-z0-9_]/g, '_')
  return /^[A-Za-z_]/.test(cleaned) ? cleaned : `_${cleaned}`
}
